<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>76c2b9b0-7732-46e3-a573-92388054723a</testSuiteGuid>
   <testCaseLink>
      <guid>bce214f9-f1aa-4780-a5f9-5fbaab29d43e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b559612b-ae55-4916-ac2d-85327777c296</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b559612b-ae55-4916-ac2d-85327777c296</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>3627f9d8-bd52-4be7-aa5f-442f9871f6d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b559612b-ae55-4916-ac2d-85327777c296</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>df281be5-32e7-491f-95ea-77c9d0cd849c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
